# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				egg = true
				arrow = true
				cow = true
				spawner_minecart = true
				magma_cube = true
				pig = true
				skeleton = true
				llama = true
				bat = true
				husk = true
				hoglin = true
				rabbit = true
				firework_rocket = true
				armor_stand = true
				giant = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				shulker = true
				salmon = true
				piglin_brute = true
				goat = true
				furnace_minecart = true
				item_frame = true
				horse = true
				minecart = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				llama_spit = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				dragon_fireball = true
				chicken = true
				donkey = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				iron_golem = true
				zombified_piglin = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				end_crystal = true
				endermite = true
				cat = true
				zombie = true
				guardian = true
				ghast = true
				sheep = true
				fireball = true
				player = true
				illusioner = true
				eye_of_ender = true
				villager = true
				tnt_minecart = true
				zombie_villager = true
				elder_guardian = true
				boat = true
				strider = true
				hopper_minecart = true
				falling_block = true
				painting = true
				cave_spider = true
				cod = true
				witch = true
				spider = true
				command_block_minecart = true

			[light_sources.settings.entities.graveyard]
				revenant = true
				skeleton_creeper = true
				ghoul = true
				nightmare = true

			[light_sources.settings.entities.gobber2]
				nemesis = true

			[light_sources.settings.entities.betteranimalsplus]
				shark = true
				deer = true
				feralwolf = true
				jellyfish = true
				piranha = true
				goose = true
				bobbit_worm = true
				songbird = true
				eel_freshwater = true
				nautilus = true
				badger = true
				eel_saltwater = true
				boar = true
				squirrel = true
				brownbear = true
				whale = true
				horseshoecrab = true
				lamprey = true
				butterfly = true
				turkey = true
				pheasant = true
				lammergeier = true
				crab = true

			[light_sources.settings.entities.betternether]
				firefly = true
				hydrogen_jellyfish = true
				skull = true
				naga = true

			[light_sources.settings.entities.earthtojavamobs]
				piebald_pig = true
				stormy_chicken = true
				dairy_cow = true
				horned_sheep = true
				cookie_cow = true
				pinto_cow = true
				pink_footed_pig = true
				fuzzy_sheep = true
				cream_cow = true
				flecked_sheep = true
				albino_cow = true
				jolly_llama = true
				fancy_chicken = true
				skeleton_wolf = true
				rainbow_sheep = true
				mottled_pig = true
				bold_striped_rabbit = true
				freckled_rabbit = true
				inky_sheep = true
				vested_rabbit = true
				skewbald_chicken = true
				patched_sheep = true

			[light_sources.settings.entities.adventurez]
				amethyst_golem = true

			[light_sources.settings.entities.betterend]
				dragonfly = true

